### ISSUE TITLE
Schemes of patterns can be developed in the framework for future works.

### ISSUE THREAD

**Issue by Myroslavachnu** [ual-cci/accelerate-immersive-framework#14]
With the help of flower pattern textile zoning in clothing and everyday objects can be created.
Also, it can be used in interior design and artistic painting.
Furthermore, the schemes of patterns can be developed in the framework for future works.

P.S.: we will add photos of works of Chernivtsi National University to illustrate those once Mick adds us :)

**Comment by joshmurr** [comment]
Maybe long term
