### ISSUE TITLE
Default camera position is not updating from inspector

### ISSUE THREAD

**Issue by micknoise** [ual-cci/accelerate-immersive-framework#17]
When using the inspector to set the default spawn point, this isn't being remembered by the document. Also if you try to add an id to the player position, it doesn't save it.

**Comment by joshmurr** [comment]
You can't add an ID in the Inspector because the Inspector uses the ID to search with in the code editor.. SO the ID is now readonly in the Inspector and the  player now has a default id of `player` which allows the edits to update the code.
